### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hex_core#6]
v0.1.0:
- [x] Add script to vendor hex_erl into other builds tools (rewrite [`vendor_hex_erl` task](https://github.com/hexpm/hex/blob/4f89e47fe0276566258fc6cfa78ad97d3b7c7211/mix.exs#L160:L180) in bash or something; include hex_erl version in generated files) (#7)
- [x] Add ETag support to `hex_repo` (#8)
- Add `hex_api` client per https://github.com/hexpm/specifications/blob/master/http_api.md
   - [x] public endpoints (get package, get release etc) (#11)
   - [x] search endpoint
   - [x] private endpoints (keys, owners etc) (#26)
   - [x] organizations support (#26)
   - [x] create user endpoint (#26)
   - [x] publish package endpoint (#26)
   - [x] Add ETag support
   - [x] ~Rate limit headers support~ (no longer applies, we return all headers)
   - [x] `URI.encode` (in Erlang) URLs (#26)

v0.2.0:
- [ ] Add  functions to build registry resources (`hex_registry:build_names` etc, ref: https://github.com/hexpm/hexpm/pull/647#discussion_r174561126)

**Comment by wojtekmach** [comment]
regarding "ETag" support I think we can do the following; change:

```erlang
-spec get_tarball(name(), version(), options()) -> {ok, tarball()}.
```

to:

1.
   ```erlang
   -spec get_tarball(name(), version(), etag(), options()) -> {ok, tarball()} | {ok, cached}.
   ```

alternatively, we could also pass it in options, I guess the users would then call it as e.g. `hex_repo:get_tarball(Name, Version, [{etag, ETag} | hex_repo:default_options()])`


2. Add `cache_dir` to options [hex_repo.erl:14](https://github.com/hexpm/hex_erl/blob/6117cb/src/hex_repo.erl#L14), and on `304 Not Modified` we read from cache; this way the successful return value is always `{ok, tarball()}`

I think we could start with 1. and later maybe add 2

**Comment by mrallen1** [comment]
I'd like to work on this, unless you've already started.

**Comment by wojtekmach** [comment]
Go for it
